export const ENABLE_MODAL = "ENABLE_MODAL";
export const DISABLE_MODAL = "DISABLE_MODAL";
export const ENABLE_SEARCH_MODE = "ENABLE_SEARCH_MODE";
export const DISABLE_SEARCH_MODE = "DISABLE_SEARCH_MODE";
